#!/usr/bin/env bash
#
# Setup script for theme switching system
# Run this after cloning dotfiles to ensure everything is configured

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DOTFILES_DIR="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || echo "$HOME/.dotfiles")"

# Colors
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

log_info() {
    echo -e "${BLUE}ℹ${NC} $*"
}

log_success() {
    echo -e "${GREEN}✓${NC} $*"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $*"
}

# Check dependencies
check_dependencies() {
    log_info "Checking dependencies..."

    local missing=()

    command -v notify-send &> /dev/null || missing+=("libnotify (notify-send)")
    command -v gsettings &> /dev/null || missing+=("gsettings")
    command -v kitty &> /dev/null || log_warning "kitty not found"
    command -v nvim &> /dev/null || log_warning "nvim not found"

    if [[ ${#missing[@]} -gt 0 ]]; then
        log_warning "Missing optional dependencies: ${missing[*]}"
        log_info "Install them for full functionality:"
        echo "  sudo apt install ${missing[*]}"  # Adjust for your distro
    fi

    log_success "Dependency check complete"
}

# Create necessary directories
create_directories() {
    log_info "Creating necessary directories..."

    mkdir -p \
        "$HOME/.cache/i3" \
        "$HOME/.config/nvim/lua/config" \
        "$HOME/.config/zsh"

    log_success "Directories created"
}

# Set initial theme state
set_initial_state() {
    log_info "Setting initial theme state..."

    if [[ ! -f "$HOME/.cache/i3/current-theme" ]]; then
        echo "dark" > "$HOME/.cache/i3/current-theme"
        log_success "Initial theme set to: dark"
    else
        log_info "Theme state already exists: $(cat "$HOME/.cache/i3/current-theme")"
    fi
}

# Make scripts executable
make_executable() {
    log_info "Making scripts executable..."

    chmod +x "$SCRIPT_DIR/toggle-theme.sh"

    log_success "Scripts are executable"
}

# Setup kitty theme
setup_kitty() {
    log_info "Setting up kitty theme..."

    local kitty_current="$HOME/.config/kitty/current-theme.conf"
    local kitty_theme_dir="$DOTFILES_DIR/config/kitty/themes"

    if [[ ! -f "$kitty_current" ]]; then
        mkdir -p "$(dirname "$kitty_current")"
        if [[ -f "$kitty_theme_dir/catppuccin-macchiato.conf" ]]; then
            cp "$kitty_theme_dir/catppuccin-macchiato.conf" "$kitty_current"
            log_success "kitty theme configured"
        else
            log_warning "kitty theme files not found at $kitty_theme_dir"
        fi
    else
        log_info "kitty theme already configured"
    fi
}

# Setup neovim theme config
setup_neovim() {
    log_info "Setting up neovim theme config..."

    local nvim_theme_config="$HOME/.config/nvim/lua/config/theme.lua"

    if [[ ! -f "$nvim_theme_config" ]]; then
        mkdir -p "$(dirname "$nvim_theme_config")"
        cat > "$nvim_theme_config" << 'EOF'
-- Auto-generated by theme switching system
local M = {
    theme = "dark",
}

function M.set_background()
    if M.theme == "light" then
        vim.o.background = "light"
    else
        vim.o.background = "dark"
    end
end

return M
EOF
        log_success "neovim theme config created"
    else
        log_info "neovim theme config already exists"
    fi
}

# Setup zsh environment for wezterm
setup_zsh_env() {
    log_info "Setting up zsh environment..."

    local zsh_env="$HOME/.config/zsh/env.zsh"

    if [[ ! -f "$zsh_env" ]]; then
        mkdir -p "$(dirname "$zsh_env")"
        echo "export WEZTERM_THEME=\"dark\"" > "$zsh_env"
        log_success "zsh environment configured"
    else
        log_info "zsh environment already exists"
    fi

    # Check if env.zsh is sourced in zshrc
    if ! grep -q "source.*config/zsh/env.zsh" "$HOME/.zshrc" 2>/dev/null; then
        log_info "Adding env.zsh to zshrc..."
        echo "" >> "$HOME/.zshrc"
        echo "# Load theme environment" >> "$HOME/.zshrc"
        echo "[ -f \"$HOME/.config/zsh/env.zsh\" ] && source \"$HOME/.config/zsh/env.zsh\"" >> "$HOME/.zshrc"
        log_success "env.zsh added to zshrc"
    fi
}

# Test theme switching
test_theme_switch() {
    log_info "Testing theme switching..."

    if "$SCRIPT_DIR/toggle-theme.sh" --help &> /dev/null; then
        log_success "toggle-theme.sh is working"

        # Show current theme
        echo ""
        log_info "Current theme: $(cat "$HOME/.cache/i3/current-theme" 2>/dev/null || echo "not set")"
        echo ""
    else
        log_warning "toggle-theme.sh test failed"
        return 1
    fi
}

# Main setup
main() {
    echo ""
    log_info "Setting up theme switching system..."
    echo ""

    check_dependencies
    create_directories
    make_executable
    set_initial_state
    setup_kitty
    setup_neovim
    setup_zsh_env
    test_theme_switch

    echo ""
    log_success "Theme switching setup complete!"
    echo ""
    log_info "Keybindings:"
    echo "  \$mod+Shift+t  - Toggle theme"
    echo "  \$mod+Shift+[  - Dark theme"
    echo "  \$mod+Shift+]  - Light theme"
    echo ""
    log_info "Test it now with: \$mod+Shift+t"
    echo ""
}

# Run setup
main "$@"
