# Gruvbox Dark
# vim:ft=kitty

## name:     Gruvbox Dark
## author:   Theme switcher
## license:  MIT
## blurb:    Warm color scheme with dark background

# The basic colors
foreground              #ebdbb2
background              #282828
selection_foreground    #ebdbb2
selection_background    #45403d
cursor                  #ebdbb2
cursor_text_color       #282828
url_color               #458588

# Kitty window border colors
active_border_color     #504945
inactive_border_color   #3c3836
bell_border_color       #d65d0e

# Tab bar colors
active_tab_foreground   #ebdbb2
active_tab_background   #3c3836
inactive_tab_foreground #a89984
inactive_tab_background #282828
tab_bar_background      #1d2021

# Colors for marks (marked text in the terminal)
mark1_foreground #ebdbb2
mark1_background #458588
mark2_foreground #ebdbb2
mark2_background #b16286
mark3_foreground #ebdbb2
mark3_background #689d6a

# The 16 terminal colors

# black
color0 #282828
color8 #928374

# red
color1 #cc241d
color9 #fb4934

# green
color2  #98971a
color10 #b8bb26

# yellow
color3  #d79921
color11 #fabd2f

# blue
color4  #458588
color12 #83a598

# magenta
color5  #b16286
color13 #d3869b

# cyan
color6  #689d6a
color14 #8ec07c

# white
color7  #a89984
color15 #7c6f64
