# Gruvbox Light
# vim:ft=kitty

## name:     Gruvbox Light
## author:   Theme switcher
## license:  MIT
## blurb:    Warm color scheme with light background

# The basic colors
foreground              #504945
background              #fbf1c7
selection_foreground    #fbf1c7
selection_background    #423b34
cursor                  #423b34
cursor_text_color       #fbf1c7
url_color               #076678

# Kitty window border colors
active_border_color     #423b34
inactive_border_color   #d5c4a1
bell_border_color       #d65d0e

# Tab bar colors
active_tab_foreground   #fbf1c7
active_tab_background   #423b34
inactive_tab_foreground #504945
inactive_tab_background #d5c4a1
tab_bar_background      #ebdbb2

# Colors for marks (marked text in the terminal)
mark1_foreground #fbf1c7
mark1_background #076678
mark2_foreground #fbf1c7
mark2_background #8f3f71
mark3_foreground #fbf1c7
mark3_background #427b58

# The 16 terminal colors

# black
color0 #fbf1c7
color8 #d5c4a1

# red
color1 #cc241d
color9 #9d0006

# green
color2  #98971a
color10 #79740e

# yellow
color3  #d79921
color11 #b57614

# blue
color4  #458588
color12 #076678

# magenta
color5  #b16286
color13 #8f3f71

# cyan
color6  #689d6a
color14 #427b58

# white
color7  #7c6f64
color15 #3c3836
